# Generated by Django 5.2.4 on 2025-08-18 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='prefix',
            field=models.CharField(choices=[('Units', 'Units'), ('g', 'g'), ('ml', 'ml')], max_length=10),
        ),
    ]
