# Generated by Django 5.2.4 on 2025-08-23 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_recipeingredient_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='prefix',
            field=models.CharField(blank=True, choices=[('', ''), ('g', 'g'), ('ml', 'ml')], max_length=10),
        ),
    ]
