# Generated by Django 5.2.4 on 2025-08-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_recipeingredient_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.CharField(choices=[('Vegetables', 'Vegetables'), ('Fruits', 'Fruits'), ('Seasoning', 'Seasoning'), ('Diary', 'Diary'), ('Meaty', 'Meaty'), ('Sweets', 'Sweets'), ('Baking', 'Baking'), ('Sauces', 'Sauces'), ('Oils', 'Oils'), ('Basic', 'Basic'), ('Fluids', 'Fluids')], max_length=30),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='prefix',
            field=models.CharField(blank=True, choices=[('', ''), ('G', 'G'), ('Ml', 'Ml'), ('Table Spoon', 'Table Spoon'), ('Tea Spoon', 'Tea Spoon')], max_length=20),
        ),
    ]
