# Generated by Django 5.2.4 on 2025-08-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_ingredient_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
        ),
    ]
