# Generated by Django 5.2.4 on 2025-08-27 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
